---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example-frontend
  labels:
    app: myapp
    tier: frontend
spec:
  storageClassName: vmc-workload-storage-policy-cluster-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example-backend
  labels:
    app: myapp	
    tier: backend
spec:
  storageClassName: vmc-workload-storage-policy-cluster-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
